#+TITLE:  理解计算机网络
#+DATE: 2020-03-02
#+CATEGORY: 网络
#+STARTUP: content
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="https://blog.geekinney.com/static/light.css"/>
#+OPTIONS: toc:nil H:2 num:2
#+INCLUDE: ../blog_site/code/post-info.org
#+TOC: headlines:2

用自己的理解来解释计算机网络的基本理论，参考书籍《计算机网络：自顶向下方法》第六版。

* 计算机网络和因特网
** 什么是英特网
   *构成描述：*

   英特网是一个世界范围的计算机网络，它连接了世界上数以亿计的计算设备。这些设备被称为主机或端系统。其中端系统通过 _通信链路_ (communication link) 和 _分组交换机_ (package switch) 连接在一起。通信链路和分组交换机统称为网络的路径(route)。

=通信链路= 有不同类型的物理媒介，包括同轴电缆、铜线、光纤和无线电频谱 。不同媒介有不同的传输速率，用比特/秒度量(bit/s或bps)。通信链路的作用是 _传输分组数据_ 。

主要的 =分组交换机= 有 路由器 和 链路层交换机 。分组交换机的作用是 _使分组数据朝着目的地转发_ 。

   *服务描述：*

英特网向应用程序提供了多种服务，应用程序一般选择其中一种向终端用户提供服务，比如电子邮件、web冲浪、即时通讯等。这些程序因为涉及到多终端间的数据交换，被称为分布式应用程序。应用程序 _不关心网络内部的数据传输及分组交换的细节_ 。它关心的是如何使用英特网服务实现终端间的数据交换。这种应用程序必须遵守的发送和接收数据的标准就是 =应用程序编程接口= (API)。

*协议：*

_协议定义了在两个或多个通信实体间交换的报文格式和次序，以及报文发送和/或接收一条报文或其它事件所采取的动作。_

** 网络边缘
   *接入网：*

   家庭接入：DSL、电缆、FTTH、拨号和卫星 / 企业(和家庭)接入：以太网和WiFi / 广域无线接入：3G和LTE

   *物理媒介：*

   双绞铜线、同轴电缆、光纤、陆地无线电信道、卫星无线电信道

** 网络核心
   网络核心是由端系统的分组交换机和通信链路构成的网状网络。

   *分组交换：*

   交换机在向输出链路传输一个分组前必须接收到整个分组。这就是交换机的 _存储转发机制_ 。该机制导致了 _存储转发时延_ 。

   分组交换机与多条链路相连，每条链路都有一个输出缓存。当某条输出链路正在工作时，同条链路到达的分组就要排队，产生 _排队时延_ 。当缓存占满时，继续到达的分组就会丢失，称为 _丢包_ 。

   源端在数据分组时会在每个分组的首部包含目的地的IP地址。分组达到路由器后，路由器根据ip地址搜索其 _转发表_ ， _转发表记录了目的地址和输出链路的映射_ ，路由器据此将分组导向合适的输出链路。

   至于，路由器的转发表是如何生成的，路由器如何选择路由最佳路径，这些都由 _路由选择协议_ 决定。

  *电路交换：*

  电路交换原理：

  分组交换与电路交换对比：

  *网络的网络：*

  今天的英特网是一个网络的网络，由十多个第一层ISP和若干不同层次的区域ISP组成。普通用户作为接入ISP向与其相连的区域IPS付费，底层次ISP向较高层次ISP付费，形成了庞大的 _层次结构_ 。除了以上的层次结构，客户ISP付费可以通过 _存在点(PoP)_ 与提供商ISP直接连接，以获取高速链路；相同层次的邻近ISP可以 _对等(peer)_ ，对等网络间不结算流量费用；第三方公司可以创建 _网络交换点(IXP)_ ， 多个ISP在IXP中共同对等。特别地，如今的 _内容提供商(如谷歌)_ 一般拥有专用网络，这种专用网络可以绕过高层ISP，与低层ISP对等或直接与接入ISP相连。以上就是如今的因特网的大概样貌。

  *分组交换中的时延、丢包和吞吐量：*
  
  * 处理时延：检查分组首部和决定将该分组导向何处所需要的时间，还包括检查比特级别的差错的时间。
  * 排队时延：分组在链路上等待传输时排队的时间。
  * 传输时延：将分组的所有比特推到链路所需的时间，受传输速率影响。
  * 传播时延：分组从链路起点到另一台路由器传播所需的时间，受传播速率影响，传播速率取决于链路的物理媒介。

  以上四种时延加一起来叫做 _节点总时延_ 。传输时延和传播时延比较 ：传输时延是将是将分组推出到链路的时间，是分组长度和传输速率的函数，与路由器间距离无关。传播时延是一个比特从一台路由器到另一台路由器传播用的时间，是路由器间距离的函数，与分组长度和链路传输速率无关。
  
  _四种时延中，排队时延是最复杂和有趣的情况_ ，因此有大量的论文和专著研究它。接下来根据自己的理解阐述排队时延的相关问题：

/首先，我们应该承认这样的事实：当比特到达队列的速率大于从队列推出比特的速率时，一定会产生排队。当比特到达队列的速率小于从队列推出比特的速率时，也不一定不会产生排队，因为多个分组可能同时到达。接下来，用数值计算来量化这一过程。/

/我们用a(单位:分组/秒)表示分组到达队列的平均速率。用R(单位:b/s)表示从队列推出比特的速率，也就是传输速率。假设每个分组都是由L比特组成的，那么比特到达队列的平均速率为 La bps 。我们将两种速率的比值 La/R 称为 _流量强度_ 。我们用它来表征时延的统计量。/

/当 =La/R > 1= 时，排队将无限增加，排队时延趋于无穷大。这和堵车是一个道理，发车的速率小于车到达的速率，车队就会越堵越长。/

/当 =La/R ≤ 1= 时，此时分组到达的时间间隔将影响排队情况。假设每 L/R 秒到达一个分组，则不会排队；假设每 (L/R)/N 秒到达N个分组，则第一个分组不用排队，后面分组都要排队且排队时延为 (n-1)L/R 。/

/实际情况是，达到队列的过程是随机，不存在周期性。此时 La/R 不能全面表征时延的统计量。此时考虑 =La/R = 0= 时，平均排队时延接近0； =La / R接近1时= 平均排队时延趋于无穷大。据此，不难画出流量强度与平均排队时延的关系图。形状类似一个从接近原点处开始的斜率不断增大的弧线，接近1时的斜率趋于正无穷。/
  










