#+TITLE: 如何有效阅读一本书
#+DATE: 2019-08-28
#+STARTUP: content
#+OPTIONS: toc:nil H:2 num:2
#+CATEGORY: 阅读
#+INCLUDE: "../code/post-info.org"
#+TOC: headlines:2

*《如何有效阅读一本书：超实用笔记读书法》 / (日) 奥野宣之 著，张晶晶 译 / 开始阅读：August 26, 2019 / 结束阅读：August 31, 2019*
* 前言
○ 无论在手机里保存多少书本，书里的内容都不会被保存在脑子里。用这本书里的关键词来比喻的话，就是这些内容既不能融入你的内心，也不能变成你无形的财富。与此相反，尽管抄完全书也不一定能记住全部内容，但某段文章、某个词、作者的语气和思想等等，都会随着抄写时的身体感觉被深深地刻印在头脑和身体里。

★ August 28, 2019\\
抄写可以加深印象，练习可以巩固知识。比如，只是看视频教程，而不动手去敲代码，相当于没有学习。
-----
○ 读一本书时要把书里的内容记在脑中，这样在几年后甚至几十年后，这些内容还能继续发酵，还会因为目前正在经历的事情而被重新回忆起来，让人们再受一次感动，甚至还想再读一次那本书。如果能像这样与一本书来一次“深刻交流”，那就再理想不过了。

★ August 28, 2019\\
好的书，好的句子在不同的情景下，不同的年纪回味，会有不一样的感觉。前提是你得记得！
_只是读过，就等于没读过。如果只是用眼睛看过，而不是记在脑子里，读再多的书也没有用。_
随着经历的丰富，偶尔会回想起高中背的一些古文诗句，有种恍然大悟的感觉。大概就是这个意思。

* 第一章：用笔管理读书生活
○ 笔记的使用方法，大体可以分为四种：
 * 随想笔记：记下平时的感悟，这与日后的选书息息相关
 * 购书清单：找到真正想读的书
 * 各种报道的剪报：尽情收录感兴趣的内容
 * 读书笔记：将读后感转变为文字保存下来

★ August 28, 2019\\
当你开始关注信息本身时，你会发现一个不一样的世界。这是一个被信息充斥的世界，每一种信息背后都有一门学问，穷尽余生我们也不可能全部了解。   
当你对信息变得敏感，很容易可以发现自己的兴趣所在，对生活也会有独到思考。
-----
○ 思考让人如同置身于迷雾中。此时此刻想到的新点子，下一秒可能就要消云散了。如果不好好做记录，恐怕就再也想不起曾经闪现的想法了。但只要把这些想法写下来、保存在纸上，就等于把迷雾装进孰料袋紧紧扎好。将这些新鲜的想法打包以后，再过多久都不会轻易遗忘。

★ August 28, 2019\\
即使是简单潦草的几个字，也会让这些灵感不至于烟消云散。
-----
○ 看到这里，你还会不会觉得这样只是把书放在一条流水线上毫无感情的处理了一遍呢？

★ August 28, 2019\\
比喻很好！
-----
○ 将笔记本一元化的技巧:
1.可以书写任何内容 2.按时间顺序记录 3.附上日期 4.灵活运用速记或略记 5.可以粘贴

★ August 28, 2019\\  
分类整理与信息一元是两种不同的哲学。两种使用场景不同，大多数时候我更倾向于后者。  
有的时候事无巨细的分类反而会降低获取信息的效率，在接近目标之前总要先思考一番它属于什么类别，在分类的时候总是纠结该如何合理划分，如何处理交叉项...这一系列动作下来简直叫人头大！我也在很多时候深受其害，宥于形式，忘了本质。   
把所有内容放在一个篮子里，简单方便。再配合搜索功能，便可快速定位信息。Mac的设计哲学就是这个样子的。

* 第二章：用购书清单指名购书

○ 通过在清单上书写这一动作，可以确认自己此次读书的目的。比如购买小说或纪实作品时，会考虑是为了享受故事、玩味文章、沉浸在作品的气氛中、了解本书的作家还是为了分析最近一段时间的文学走向；比如购买商业书籍时，则会考虑是为了要以后运用到工作或者兴趣爱好中、方便传授给他人、提高自身涵养还是为了能够立即付诸实践。

★ August 28, 2019\\ 
不同类型的书特点不同，也导致了的阅读方式、阅读目的、做读书笔记的方式的差异化。  
小说我主要看描写、遣词造句的技巧，故事节奏的把控，悬疑的铺陈等。  
方法介绍类书籍主要把握思想要点，可以快速阅读。
-----
○ 所谓阅读的动机或目的性，就好比照片的“焦点”。即使拍摄同样的场景，聚焦于面前的花朵和聚焦于远处的建筑，得到的效果完全不同。读书也一样，抱着不同的目的阅读同一本书，也会产生截然不同的效果。

★ August 28, 2019\\ 
相机焦点的比喻很好。
-----
○ 选择图书，重要的是看平时收集的信息，要经常竖起敏感的天线。平时提高了敏感度，就算没有特意去找，也能在日常生活中收集很多有意思的信息。这样积累下去，想读的书要多少有多少，根本不需要去网上搜索。

★ August 28, 2019\\ 
“敏感的天线”，很形象的比喻！博闻强识的人遇到任何的话题都能聊出点东西来，要么是生活阅历丰富，要么就是博览群书。如是种种，必定是对生活充满好奇之心。  
这种好奇心就是《奇风岁月》中描述的“神秘力量”，是丰子恺笔下的插画，是钱钟书眼中的“蚊帐游戏”，是宫崎骏的动画，是每一个孩子眼中的世界和大人眼中的孩子。  
关于童心、好奇心、想象力...的话题，是很值得被研究和探讨的。
-----
○ 这样考虑可能更容易理解：潜水艇有“主动声纳”和”被动声纳“两种声纳系统。主动声纳是靠自身发出的声波反射状态来进行计量的，而被动声纳则是考接受其他船只或潜水艇发出的声波来活动的。也许你觉得主动声纳听起来更厉害，但得到广泛使用的恰恰是被动声纳系统。

人类也是，最先贯彻的应该是”被动声纳“，也就是通过报纸、杂志、书籍和电视等途径，尽可能多地捕捉日常中接触的信息，把感兴趣的书名或主题都写在笔记本上的随想笔记里。

★ August 28, 2019\\ 
声纳的比喻很形象。先是被动接收，然后主动创造，很多事情好像都有这么个道理。

* 第三章：用笔记把读过的书变成精神财富
○ 至于能否得心应手的做好读书笔记，进而熟练的参考记录过的笔记，都是坚持写读书笔记几年甚至是几十年后才能收到的效果。所以，为了达到这样的境界，一切都应该以“能坚持下去”为先。

★ September 01, 2019\\  
这一点太关键了！哪怕只是记录一句话，写和不写是有很大差别的。决定坚持做一件事情就要持续不断的做下去，中途间断了一次就会有间断第二次的可能，第三次，第四次...最后就会放弃。最好的办法是不要间断，让记录的过程变的简单。鲁迅先生有写日记的习惯。如果当天没有特别的事情，他也会记上一句“今日无事”。
-----
○ 只要记得重点放在“摘抄对自己来说很重要的文章”和”写主观评论”上即可。即使客观上很重要，如果眼前的信息无法与自己在感性层面上产生共鸣，那么再读多少次也不会有感悟。

★ September 01, 2019\\
之前总会担心漏掉一些重要的句子，其实不必担心。读不懂和没有感触的内容，即使客观上重要，也无需摘抄。无需像做语文阅读理解，非要给一段文字编造出什么意义来...
-----
○ 如果在一本书做了很多标记，那么在写读书笔记之前还是暂时将其放置一段时间吧。即使是读完后认为受益匪浅的书，过一段时间以后也会变得“不过如此”。需要摘抄的内容也会随之减少。

★ September 01, 2019\\
受情绪影响，我们大概率会作出不恰当的判断，但时间是试金石。有价值的内容在时间洗礼后仍能熠熠发光，我们的判断在时间的沉淀中愈发的趋于理性。当不确信自己的判断或决定是否适合时，不妨等一等。
-----
○ 好主意不会凭空出现。不论是什么想法，都一定是对某种刺激作出的回应。所以，只有看到一个名为“好书”的好球飞过来，我们才能打出那个名为”好主意“的绝妙击球。

★ September 01, 2019\\
主观印象是对客观实在的反应。晚上做的梦是平时所思所感的排列组合，不可能创造出毫无根据的外星人形象.... 新的思考总是建立在旧思考基础上的，读书时获得的感想就是原创思考的源泉。
-----
○ 请找到那本能够成就自己的书。失落的时候，走投无路无路的时候那本书都会成为自己的心灵支柱。

★ September 01, 2019\\
很想感受这种通过一本书找到心灵支柱的感觉。现在人们的生活不那么困难了，应该很难有这种深刻的体验了吧。据我所知，在困苦的年代，一本好书确实可以成为一个人活下去的动力与希望。《约翰.克里斯朵夫》就是这样一本书！

* 第四章：通过重读笔记提高自我

本章讲诉读书笔记法的最后一个步骤：活用。

○ *学以致用的读书体验*

做读书笔记为什么一定要写下自己的感想？因为对读完的内容进行主动思考，才能真正掌握书本中的内容。在读书笔记中再生产出原创文章，就像把一把刀磨得更锋利。原创文章中的思想也一定是更细致、深刻的。

○ *积极输出促进思想内化*  

我们一定有过这样的体验，想别人传达自己的想法时，一开始杂乱无章的语言表达在叙述的过程中会逐渐清晰和有逻辑，这是最常见的思想输出。哪怕是我们非常了解的事情，一旦需要向别人说明或者写下来，还是会有很多模糊不清的内容。事后，再查阅资料，重新审视自己的观点，建立起思想体系，我们就会有所提高。

○ *在固定场景中重读笔记*

为了重读时能集中精神，易于坚持，建议在固定的场景重读读书笔记。睡前，洗澡后，通勤途中或无聊的时候...选择适合自己的时间段即可。总之，要为重读笔记营造一个轻松愉快的氛围，好像处于好奇而翻旧报纸，为了消磨时间而翻开字典或图鉴一样，在不知不觉中吸收信息。当你翻开两三个月以前的笔记时，说不定会惊讶：“原来我还读过这本书名，我竟然有过这么奇怪的想法”。这就是重读笔记带来的惊喜。

○ *养成重读的习惯*

把重读笔记加入日程中，找了能够集中精力思考的地方重读和写读书笔记，多思考怎样写更方便日后阅读。

○ *在重读过程中有所收获*

曾经不理解的内容在重读时可能会恍然大悟。关键要记录下当时真实的想法和思考，为新的发现做准备。在我看来，所有的笔记性工作，日记也好，读书笔记也罢，真正要价值，有意义的地方在于重读或回顾。只是记录一遍收效甚微，重读可以将记录的价值无限放大。

○ *通过重读为思想增色*  

根据自己对参考的需求，安排重读的策略：
想要简单回顾时，重读读书笔记；想回忆起更多时，参考书中的重要段落；想重头开始看起时，重读原书。

如果把一本书比作一个场所，那么读书笔记就是在这个场所拍摄的照片。在不同的时间去同一个场所拍照，拍出来的照片都会有所不同，4而过一段时间再去看这些照片，对那个场所的印象也会发生变化。

遇到现实中的问题，多想想“那本书里是怎么说的””那位作者是怎么说的“，像这样退几步考虑大局，就可以避免目光短浅地下结论。

○ *过去的读书体验在读书生活中的运用*

读书的时候，学会“事先扫平障碍”，先读简单的部分有助于理解较难的内容。读书笔记也可以逐章、逐项的写，这样会比从头到尾读一遍理解更深刻。读较难的专业书可以先读简单的相关书籍来过渡。理解同一个作者的观点时，也可以读不同时期的书参考比较。

