#+TITLE: 2020年2月总结
#+DATE: 2020-03-01
#+CATEGORY: 总结
#+STARTUP: content
#+OPTIONS: toc:nil H:2 num:2
#+INCLUDE: ../code/post-info.org
#+TOC: headlines:2

这是我使用orgmode管理日程以来写的第一篇月总结。虽然我一直有这个想法，并且清楚的认识到“月总结”的重要性，但由于形式与流程上的不完善，迟迟没有动笔。经过了这一个月“过山车”似的状态调整与个人反思，我在2020年3月份的第一天写下了我人生的第一份自发而为的“月度总结”。这是一个开始，一个重要的开始！

自律是个漫长且煎熬的过程。从我折腾orgAgenda开始，从决定考研开始，我就下定了决心和以前拖延懒惰的自己决裂。这一个月的经历便是很好的印证。

*阶段总结*

这一个月晨间日记的书写断断续续，我的状态变化也是起起伏伏。前五天沉迷《星露谷物语》，因为爸妈不在御景城，几个通宵都在玩NS。《星露谷物语》让我体验了一把“经营养殖钓鱼”的虚拟生活，但是熬夜和无规律的生活也给我造成了身体上的不适和精神上的压力。后面妈妈到御景城后生活就规律了许多。

23号之前的状态基本是早上起来就折腾blog或emacs，中午睡觉到很晚才起来，晚上和老妈一起看剧。或者一整天在边看剧边折腾电脑。晚上也基本是折腾blog或elisp到很晚才睡。这样的恶性循环使自己沉迷在折腾的兴奋状态中，日记写的断断续续，也没有认真的反思过。

直到23号，情况有了一点好转。我开始着手复习数据结构，时间的利用率变高了些。但是，过度折腾的情况还是没有避免，25、26、27不是过度折腾blog，就是过度hack emacs。27号晚认真反思，找到了解决的办法：计时。一天的生活之所以让自己不满意，大多情况是因为过度折腾造成精力消耗，然后便没有了学习的精神。没精力的时候，要么是在睡觉，要么就是在看剧或ZW....所以“计时”能够让我对折腾的时间有个概念。“番茄时钟”每25分钟休息一次也对精力有一定的补充。

28，29号两天，我按照番茄时钟严格计时，结果是相当的满意。复习的时间得到了保证，折腾的计划又没有落下。这两天复习完了数据结构的“线性表和栈”的内容，完成了blog样式的改版，收到了多条评论。感觉真棒！这样的状态是很不错了，但是对于考研复习还不够，后面继续调整。

当然，所有的功劳不能全部归于“番茄时钟”，我的“org agenda”也功不可没！前期的折腾没有白费，舒服有序的orgAgenda界面让我对要完成的任务、规划的项目心中有数，这种按照计划循序渐进完成的感觉促使我在不断往前走。

*下阶段思考*

除了把每天的事情做好，还得对计划有个整体的把握，这是看b站阅读up主视频给我的启发。比如，每周、每月一定要完成的几件事情，项目的进度预期等。这种宏观上的把握会让每天的任务执行更有信心和动力。

=复习=\\
3月份，争取初步复习完数据结构，把书上的基本算法全部实现一遍，并做总结。这意味着每天的有效复习时间得得到保证。复习时间计划至少5个小时，晚上的时间也要利用起来。下周日之前复习完数据结构第五章。

=阅读=\\
3月份，读完《傅雷家书》并做完读书笔记。阅读是我的兴趣，是我着力想培养的一个习惯，但不是当下最重要的事情。所以不要因为阅读这件事影响复习的时间。所以三月份搞定一本《傅雷家书》就够了。每天抽出40分钟时间阅读就能够完成了。

=跑步=\\
跑步并不是时间越长也好，次数越多越好，过度运动对人的心肺不仅无利还会有害。所以，以前我的一些简单粗暴的想法是该该改了。3月份计划一周跑四次步，周一周二跑，周三休息一天，周四周五跑，周六周日休息两天。跑步时长，根据身体状态控制在20~40分钟之间。慢跑为主。

=其他=\\
想做的事情很多，时间和精力总是有限的。如果每件想做的事情都要规划，所有的事情便都做不好。以上三件是我认为当下最重要的，其余的事情按照GTD的流程来做就行。
