* web前端习笔记
** PS基础
   - 不同图片格式在网页中的使用：
   - JPG 网页高清大图
   - GIF 网页小图标（支持动画，透明）
   - PNG8 网页小图标，透明
   - PNG24 支持透明，半透明
   - ctr+t 自由变换
   - 盖印可见图层

** HTML和CSS基础
   - 图片标签
     <img src=".." alt="图片名字" />
	
   - a标签：
     - 链接
       <a href="http://www.baidu.com/">a标签 链接</a>
       <a href="http://www.baidu.com/" target="_blank">a标签 跳转新页面 _self为当前页面</a>
       统一在头部定义页面跳转方式: <base target="_blank" />
     - 下载
       <a href="文件路径">下载文件</a>
     - 锚点（页内跳转）
       <a href="#box">通过div中的id识别跳转不同的块</a>

   - strong标签：<strong>中间文字强调为粗体</strong>

   - em标签：<em>中间文字强调为斜体</em>

   - span标签: <span ...>区分样式</span>

   - 列表标签：
     有序列表 <ol><li>内容</li>....</ol>
     无序列表 <ul><li>内容</li>....</ul>
     定义列表 <dl><dt>标题</dt><dd>内容</dd></dl>

   - 基础选择符：
     id选择符 #box{..}
     群组选择符 #box1,#box2,#box3{...}
     class选择符 .box{...} .box1{...}  <div class="box box1"></div>
     类型选择符 div p{..} //div包含的p标签
     通配符 *{..} //所有元素

   - 样式优先级：
     同级样式后者覆盖前者
     类型选择符(1)< class(10)< id(100)< style行间样式(1000)< js

   - 伪类详解:
     link 链接未访问
     hover 鼠标悬停
     active 链接激活
     visited 访问过后
     a伪类全部支持，其他标签一般只支持hover
     形如a:hover{...} div:hover{...}

   - 标签特性：
     默认样式重置，确保兼容性(css reset)
     <style>
     body,p,h1,h2,h3,h4,h5,h6,dl,dd{margin:0; font-size:12px;/* font-family:XX; */}
     ol,ul{list-style:none;padding:0;margin:0;}
     a{text-decoration:none;}
     img{border:none;}
     </style>

     text-indent:20px;缩进
  
   - 标签分类：
     - 内嵌(inline)
       同行跟同类型标签
       内容撑开长度
       不支持宽高
       不支持内外边距
       代码换行被解析
       转换 diaplay:block
       转换 diaplay:inline-block

     - 块(block)
       独占一行
       没有宽度时，撑满一行
       支持所有CSS命令
       转换 display:inline
       转换 display:inline-block

     - 图片(inline-block)
       块在一行显示
       行内属性支持宽高
       没宽度时内容撑开宽度
   
   - 光标类型：cursor:pointer/text/move....
     <标签 title="元素提示信息">
   
   - 浮动 float:left/right/none 元素加了浮动，会脱离文档流，按照一定的方向移动，碰到父级的边界或另一个浮动元素停止
     使块元素在同一行显示
     使内嵌元素支持宽高
     没宽度时内容撑开宽度
     脱离文档流
     提升层级半级
     clear:left/right/both/none 元素在某个方向上不能有浮动元素 
	  
   - 清浮动
     给父级加浮动
     给父级加display:inlin-block
     在浮动元素下方加清浮动div:(IE6有最小高度问题)
     <div class="clear"></div>
     .clear{height:0;font-size:0;clear:both;}
     在浮动元素下方加 <br clesar="all" /> //不符合W3C标准
     *推荐？？*给浮动元素父级加上{zoom:1}  :after{content:""; diplay:block; clear:both;}
	  
   - overflow
     给父级加，可以清浮动（IE6不行）
     overflow:auto 溢出时显示滚动条
     overflow:auto 默认显示滚动条
     overflow:auto 溢出时隐藏
	  
   - IE6下双边距BUG：块元素浮动和横向margin时，横向margin值放大两倍
     解决：display:inline

   - 标签嵌套时，p标签里不能嵌套块标签 

   - 相对定位 position:relative
     a.不影响元素本身特性
     b.不使元素脱离文档流
     c.定位元素位置控制 top/bottom/left/right:..px

   - 绝对定位 position:absolute
     a.使元素完全脱离文档流
     b.使内嵌支持宽高
     c.块属性标签内容撑开宽度
     d.默认后者层级高于前者
     e.如果有定位父级，绝对定位相对于定位父级偏移，没有则相对于整个文档偏移

   - 定位层级 z-index:[number]   z-index:1;使元素出来

   - 滤镜
     标准 不透明度：opacity:0~1
     IE私有滤镜 filter:alpha(opacity=0~100)  
    
   - 表格
     重置默认样式：
     th,td{padding:0;}
     table{border-collapse:collapse}
     table标签的基本特性是display:table
     table决定了整个表格的宽度
     表格里每一列必须要宽度，单元格宽度转换成百分比
     合并：colspan, rowspan
	  
   - 表单
     重置默认样式：
     form{margin:0}
     input{padding:0;margin:0;}
     select{margin:0;}
     textarea{margin:0;padding:0;resize:none;overflow:auto;outline:none(焦点线)}
     解决input背景滚动：加div

** HTML5
*** 语义化标签
    - <header>页面头部</header>
    - <footer>页面底部</footer>
    - <nav>导航</nav>
    - <hgroup>标题组合</hgroup>
    - <section>区域划分</section>
    - <article>主体，独立的一块内容，帖子</article>
    - <aside>和主题相关的附属信息</aside>
    - <figure>媒体元素,图片视频  <figcaption>文字描述</figcaption> </figure>
    - <time></time>

    - <input type="text" list="valList">
    - <datalist id="valList">text的提示信息
      <option value="css">css</option>
      <option></option>
      </datalist>
    - <details open> 详情信息
      <summary></summary>
      <p></p>
      </details>
    - <address>作者信息</address>
    - <mark></mark>  <keygen>公钥</keygen>
    - <progress max="" value="">进度条
      <span>70</span>% 保证兼容性
      </progress>
    - 自定义标签：兼容低版本IE
    - <script>document.creatElement("")</script>
    - 或使用插件：html5shiv.js

*** 新增表单控件
    - <input type="email"/>
    - <input type="tel"/>
    - <input type="url"/>
    - <input type="search"/>
    - <input type="range" step="2" min="0" max="10" value="4"/> 数值选择器
    - <input type="number"/>
    - <input type="color"/>
    - <input type="datatime"/> UTC时间
    - <input type="datatime-local"/>
    - <input type="time"/>时分秒
    - <input type="data"/>年月日
    - <input type="week"/><input type="month"/>

*** 特效和属性函数
    - <input type="text" placeholder="请输入用户名"/>提示信息
    - <input type="text" placeholder="请输入用户名" autocomplete="off" />是否保存输入值的提示
    - <input type="password" autofocus/>自动获得焦点
    - <input type="password" requred pattern="\d{1,5}"/>不能为空,正则校验
    - formaction="url",保存至草稿箱

*** 表单验证反馈
    - 新选择器
      document.querySelector(".div")
    - eval:可以解析任何字符串变成json
    - parse:只能解析JSON形式的符串变成json，更安全
    - stringify:把json转成字符串。

    [看到2.2 json的新方法]
** CSS3
   - 圆角：border-radius:20px 40px;
   - 椭圆：border-radius:x轴半径/y轴半径;或用百分
** JS初级
   - 动态给元素加class,改变样式：oP.className='red';
   - 不允许条件判断：img路径，链接，颜色，innerHTML
   - oDiv.style['width'],方括号中值可修改。
     js中允许把"."换成"[]"
   - 数组
     var arr=[];
     arr.push();往数组最后加数据。
   - getElementByTagName 动态方法：
     找到标签元素的集合，即使有一个，也要加[0],前面不一定用document，根据需要用父级查找。
   - document.title='';
   - document.body.innerHTML='';
   - 用js修改css样式，相当于加行间样式，行间样式比外部样式优先级高，故可修改，当使用多个时，后者覆盖前者。cssText只能设置一次！！！！！！！
     oDiv.style.width='100px';或
     oDiv.style.cssText='width:100px;height:100px;....';
   - 开关的作用onOFF
     this：指的是调用当前方法函数的对象。
     一个开关只能控制一组，多组需要用自定义属性。
     循环中用this来查找当前对象！
   - 索引：aBtn[i].index=i;将一组相同标签与index匹配。
   - js中的数据类型：
     数字、字符串、布尔、函数、对象(obj、[]、{}、null)、未定义
     Number();字符串转数字：json,未定义，函数无法转，其他可以转。
     parseInt(a,10);从左往右一个个转换成数字，遇到非数字结束，认识加减号空格，不认小数点。(10表示转的进制)
     pareFloat();认识小数点。
     可将parseInt和parseFloat结合判断是整数还是小数。
   - NaN:不是数字的数字类型。
     NaN是假，NaN表示进行了非法运算，NaN和自己不相等。
     isNaN();判断某些值是不是数字。true：不是数字；false：是数字。
     内部依据number转换。
   - 函数传参：重用代码。
     * 尽量保证 HTML 代码结构一致，可以通过父级选取子元素
     * 把核心主程序实现，用函数包起来
     * 把每组里不同的值找出来，通过传参实现
   - JS作用域：“JS解析器”
     * “找一些东西”：var  function 参数
       a = ...	所有的变量，在正式运行代码之前，都提前赋了一个值：未定义
       fn1 = function fn1(){ alert(2); }所有的函数，在正式运行代码之前，都是整个函数块
       JS 的预解析,遇到重名的：只留一个;变量和函数重名了，就只留下函数。
     * 逐行解读代码：表达式：= + - * / % ++ -- ! 参数……;表达式可以修改预解析的值！
   - 运算符和流程控制。
     取模：i%=5（0，1，2，3，4）：循环上色，时间转换。
     ‘200’==200，200===200（类型数值全等）
     ！：反选。	
     Break(跳出循环) 	continue(跳过本次)
   - 函数详解
   - Arguments：实参的集合，不写形参也可以，函数参数个数无法确定时用。
   - 获取样式：
     getComputedStyle();获取浏览器计算后的样式。//IE6,7,8不兼容
     $(‘div’).currentStyle.width  标准浏览器不兼容。
     结合使用：
     If($(‘div’).currentStyle){
     alert($(‘div’).currentStyle.width);
     }else{
     alert(getComputedStyle($(‘div1’)).width);;
     }
     注意：不要获取复合样式，获取单一样式，不要有空格。
   - 定时器：
     * Var timer = setInterval(函数，毫秒) 重复执行
       clearInterval(timer)  清除
       先清除定时器，再开，避免开多个定时器。
     * var timer = setTimeout(函数，毫秒); 执行一次。
       clearInterval(timer)  清除
   - 系统时间对象,全部是Number类型。
     var myTime = new Date();
     var iYear = myTime.getFullYear();//getMonth+1(月份要加一),getDay,getDate(日)
     getDay();//星期
   - 字符串
     str.charAt();
     str.charCodeAt();根据汉字找编码。
     String.fromCharCode(21678);根据编码返回汉字。//0~9：48~57 //a~z:97~122 //A~Z:65~90
     str.indexOf(‘m’); 从头开始找。
     str.indexOf(‘m’, 5);从第5位开始找。//找不到字符串返回-1
     str.lastIndexOf(); 从后往前找。
     字符串比较：比第一个字符的unicode编码。
     str.substring(0,2); 截取字符串, 负数当作0，交换位置
     str.slice(0,2); 截取字符串,不交换位置,负数从后往前取。
     str.toUpperCase(); 转成大写
     str.toLowerCase(); 转成小写
     str.split(‘.’, 3); 以点为分隔符，划分为数组,后一个参数为截取几段，可选。
     str.split(‘’, 3); 分割每个字母。 
     str.join(); 把数组连接成字符串，中间有逗号。
     str.join(‘’); 把数组连接成字符串，中间没有逗号。参数为连接符。 
     oP.innerHTML.split(str).join(‘<span>’+str+’</span>’); 查找替换。
   - Json与数组
     var json1 = { name’: ‘Leo’, ‘age’: 23};
     var arr = [{‘name’: ‘Leo’, ‘age’: 23},{‘name’: ‘Kinney, ‘age’: 24}];
     for (var attr in json1) {alert(json1.attr)};//j2son1[attr]
     json只能用for in遍历，数组既可以用for循环也可以用for in。
     var arr = new Array(4); //创建长度为4的数组。
     arr.length 可读可写，  arr.length=0 //清空数组
     数组最后添加：arr.push(); 返回值为数组的长度。
     数组前面添加：arr.unshift(); 返回值为数组的长度,IE67不兼容返回值。
     数组删除最后一个：arr.pop(); //返回值为删掉的元素
     数组删除第一个：arr.shift(); ///返回值为删掉的元素
     arr.unshift(arr.pop()); //把最后一个移到最前面。往后移动
     arr.push(arr.shift()); //把最前一个移到最后。往前移动
     数组的splice方法：
     arr.splice( 0, 2 ) //从第0位开始删2两个。返回删除的内容
     arr.splice( 0, 2, ‘kinney’ ); //替换前两个为kinney。返回删除的内容
     arr.splice( 1, 0, ‘kinney’ ); //在第1位前添加kinney。返回为空。
     数组排序：
     arr.sort(function (a,b) {
     return a-b; //从小到大排序
     return b-a; //从大到小排序   //原理：a,b为随机从数组中依次取的值，相减大于0，则交换位置。	
     } );
     数组打乱：
     arr.sort(function(){
     return Math.random()-0.5; //Math.random()随机产生0~1之间的数字。
     });
     Math方法：
     Math.round(); 四舍五入。
     返回x~y之间的随机数：
     Math.round( Math.random()*(y-x)+x );
     返回 0~x之间随机数：Math.round( Math.random()*x );
     返回 1~x之间随机数：Math.ceil( Math.random()*x ); //向上取整
     连接两个数组：arr1.concat(arr2);
     颠倒数组元素位置：arr.reverse();
     字符串字符颠倒：
     var str = “abcdefg”; str.split(‘’).reverse().join(‘’);

** JS中级
   * DOM操作
     文档对象模型
     childNodes：子节点列表集合，只读属性。有兼容性问题（不推荐！）
     标准(Chorm,FireFox,IE9)下包含文本节点和元素节点和非法嵌套的子节点，非标准下只包含元素节点。
     attributes：只读属性，属性列表集合。
     元素.attributes[0].name/value
   * NodeType：只读属性，当前元素的节点类型。
   * children：子节点列表集合，只读属性。标准下，只包含元素类型的节点（允许非法嵌套）。非标准下，只包含元素类型的节点（非法嵌套解析为子节点）。
   * firstChild:类似childNodes，第一个节点，有兼容性问题。
   * firstElementChild:第一个元素节点。(标准下)
   * 结合使用：var oFirst = oUl.firstElementChild || oUl.firstChild;
   * 推荐使用 children[0]
   * lastChild, lastElementChild
   * nextSibling, nextElementSibling 下一个兄弟节点
   * previousSibling, previous ElementSibling 类似！！ 上一个兄弟节点。
   * parentNode 当前节点的父节点，没有兼容问题。
   * offsetParent 离当前元素最近的有定位的父节点，默认body。Ie7以下，当前元素有定位，为html。
   * offsetLeft/offsetTop: 只读属性 当前元素到定位父级的距离。
   * ie7及以下：如果自己没有定位，offset…是到body的距离。
     自己有定位，到定位父级的距离。没有定位父级，到html的距离。
   * 宽高取值
     oDiv .style.width 样式宽，有单位
     oDiv.clientWidth 可视区宽（样式宽+padding），没有单位。
     oDiv.offsetWidth 占位宽（样式宽+padding+border）没有单位。
     获取元素到页面的绝对定位：
     var iTop = 0；var obj = oDiv3; while(obj) { iTop += obj.offsetTop; obj = obj.offsetParent; }
     封装成getPos函数
   * 动态创建元素
     document.createElement('');
   * appendChild 插入子节点
   * insertBefore
     父级.insertbefore(新元素，被插入的元素)
     ie下被插入节点不存在时，报错。
     if(oUl.children[0]){
     oUl.insertBefore(oLi,oUl.children[0])
     }else{
     oUl.appendChild(oLi);
     }
   * removeChild 删除节点
     父级.removechild
   * repalceChild 替换子节点
     父级.replaceChild(新节点，被替换节点)
   * getElementsByClassName
   * addClass函数
   * removeClass函数
   * 表格操作
     * 

** 注意：
   1. 注意是否加引号，获取的对象不加，属性名称要加。alert( getStyle( oDiv, 'marginLeft' ) );
      只能return一个值！判断用哪种方式获取元素，然后return一个。
   2. 要修改的样式值需要在css样式中存在。Left值的问题
   3. if else和else if的问题，if else非此则彼，else if条件满足才执行！
* Vue.js 学习笔记
** 初识Vue.js
   * vue采用了MVVM设计模式(模型-视图-视图模型)
   * 基本开发模式：引入vue.js框架后，在body的底部使用new Vue()方法创建一个实例
   * 数据驱动DOM是Vue.js的核心理念，所以不到万不得已不要主动操作DOM，只需要维护好数据，DOM的事Vue会帮你优雅的处理

** 数据绑定
*** 实例与数据绑定
    * 结构理解
      * 通过构造函数Vue创建一个Vue的根实例，所有的代码都写在这个实例的选项内
      * el选项：el用于指向页面中已经存在的DOM元素来挂载Vue实例
      * 标签上的v-model属性的值对应Vue实例中的data选项中的字段，这就是数据绑定
      * 双向绑定：修改属性，数据会变化；修改数据，属性也会变化
    * 生命周期
      * created:实例创建完后调用，尚未挂载元素
      * mounted:el挂载到实例上后调用
      * beforeDestroy:实例销毁前调用
    * 插值与表达式
      * 在双打括号中添加绑定的属性值：{{ name }}
      * 可以进行属性值的简单的js运算,三元运算。{{ num /10 }},{{ text.split(',').reverse().join(',') }}
    * 过滤器
      * 在插值的尾部添加‘|’管道进行过滤：{{ date | formatDate }}
      * 过滤器函数的定义放在vue实例的filters选项内
      * 过滤器可以串联也可以接收参数：{{ message | filterA('arg1', 'arg2') }}. arg1和arg2是第二和第三个参数，第一个参数是数据本身
*** 指令与事件
    * 指令的主要职责是当表达式的值改变时，相应的将某些行为应用到DOM上
    * v-bind:动态更新HTML元素的属性, <a v-bind:href="url">链接</a>
    * v-on:绑定事件监听器，事件函数放在methods选项中, <button v-on:click="handleClose"〉点击隐藏</button>
    * 表达式除了方法名， 也可以直接是一个内联语旬, <button v-on:click="show = false”〉点击隐藏</button>
*** 语法糖
    * v-bind用':'代替. <a :href="url">链接</a>
    * v-on用'@'代替. <button @click="handleClose">点击隐藏</button>

** 计算属性
*** 概念
    * 当模版中的表达式过长或逻辑过复杂时，会很难阅读和维护，此时使用计算属性
    * 所有的计算属性以函数的形式写在vue实例的computed选项中，并返回计算结果
*** 用法
    * 计算属性可以依赖多个vue实例的数据，只要其中中的任一数据变化，计算属性就会重新执行，视图会更新
*** 计算属性缓存
    * 在模版中可以用方法或者计算属性获得计算的值。{{ reversedText() }}或{{ reversedText }}
    * 使用计算属性存在缓存，只有数据发生变化时才会重新计算值
    * 使用方法调用时，只要重新渲染，函数就会被调用
    * 当遍历大数组，做大量计算时，应该使用计算属性
      
** 内置指令
*** v-cloak
    * 解决插值表达式闪烁
    * 只替换自己的占位符
    * <p v-cloak>++++{{msg}}----</p>
*** v-text
    * 没有闪烁问题
    * 覆盖元素中原来的内容
    * <p v-text="msg"></p>
*** v-html
    * 将数据渲染成html
*** v-bind:
    * 属性绑定
    * 单向数据绑定，M->V
    * 将属性的值当作变量，在Vue实例中查找该值
    * 语法糖为“:”
    * :title="mytitle"
*** v-on
    * 事件绑定
    * v-on:click="show"
    * 在Vue实例中创建methods属性
      #+BEGIN_SRC js
	methods:{
	    show:function(){
		alert('hello Vue.js')
	    }
	}
      #+END_SRC
    * 语法糖：@
*** v-model
    * 双向数据绑定
    * 只能用在表单元素上

*** v-for
    * 循环数组：<p v-for="(item, i) in list">索引：{{i}}---值：{{item}}</p>
    * 循环对象数组：.....
    * 循环对象：<p v-for="(val, key) in user">值：{{val}}---键：{{key}}</p>
    * 循环数字：值从1开始
    * 在组件中使用v-for时，key属性是必须的
      * key只能用number.string
      * 使用v-bind指定key的值
      * <p v-for="item in list" :key="item.id"></p>
*** v-if & v-show
    * v-if每次都会重新删除创建元素，切换性能消耗较高(元素需要频繁切换不使用)
    * v-show只是改变了元素的display:none属性，初始渲染消耗较高(元素不显示时不使用)
** 事件修饰副符
*** stop
    * 阻止冒泡
    * 事件只作用于自身，所有上级都不能触发
*** prevent
    * 阻止默认行为
    * 比如阻止链接跳转，阻止表单提交
*** capture
    * 捕获触发事件
    * 从外往里
*** self
    * 只有点击当前元素才会触发，不允许冒泡，捕获执行触发
    * 只阻止自己的冒泡，捕获，不阻止其他元素
*** once
    * 只触发一次
** vue中css样式
*** 使用class样式
    * 使用数组：<p :class="['thin', 'italic', 'red']">this is content</p>
    * 三元组：<p :class="['thin', flag?'red':'']">this is content</p>
    * 数组嵌套对象：<p :class="['thin', {'active':flag}]">this is content</p>, (flags数据保存在vue中)
    * 直接使用对象：<p :class="classObj"></p>
      #+BEGIN_SRC js
	    <p :class="classObj">content</p>
	    data: {
		classObj: {
		    thin: true,
		    red: true,
		    active: false,
		}
	    }
      #+END_SRC
*** 使用style内联样式
    * 直接绑定style：<p :style="{color:'red', 'font-weight':200}">content</p>
    * 将第一个的style中的对象移到vue的data中
    * 绑定多个对象：<p :style="[style1, style2]">content</p>
** 自定义过滤器
   #+BEGIN_SRC js
     Vue.filter('msgFormat', function(msg, arg){
	 return msg.replace('/单纯/g', arg)
     })
   #+END_SRC
   * function第一个参数为要处理的变量，后面的参数为过滤器传递的参数
   * 全局过滤器在script标签下定义
   * 私有过滤器定义在Vue实例中，用filters属性表示
   * 填充日期：(dt.getMonth()+1).toString().padStart(2, '0')
** 自定义按键修饰符
   * @keyup.enter="add",(键盘事件后为按键名或键盘码)
   * 自定义按键修饰符：Vue.config.keyCodes.f2 = 113
** 自定义指令
   * 定义v-focus, 自动获取焦点
     #+BEGIN_SRC js
       Vue.directive('focus', { //第一个参数为指令名称，调用时加“v-”
	   bind: function(el, bingding){ //第一个参数永远是el，表示绑定指令的元素
	       el.focus()  //和样式相关的行为
	   },
	   inserted: function(el){
	       el.focus()  //和js行为相关的操作
	   },
	   updated: function(){
	   //节点更新时调用
	   }
       })
     #+END_SRC
   * 定义私有指令：vue实例中添加directives属性
   * 简写：将名称后面的对象换成函数(默认写到bind和updated中)
** 生命周期
   * beforeCreate()执行时, data,methods都未被初始化
   * created()执行时，都已经初始化
   * beforeMount()执行时，模版已经在内存编译完成，但尚未渲染到页面
   * mounted()执行时，内存中模版已经挂载到vue，用户可以看到渲染好的页面。实例已经被完全创建完成
   * beforeUpdate(), 数据被改变，页面没有更新
   * updated(), 页面更新
   * beforeDestroy(), 所有的data,methods,filter,指令...都处于可用状态
   * destroy(), 组建完全销毁
** 发送数据请求
   * 使用vue-resource包
   * this.$http.get('url').then(function(result){})
   * this.$http.get('url').then(result => {})
   * ajax在created()方法中调用
     #+BEGIN_SRC js
       getAllList(){
	   this.$http.post('url',
			   {name, this.name},
			   {emulateJSON: true}
			  ).then(result => {
			      if(result,body.status == 0){
				  //成功
				  this.getAllList()
			      }else{
				  //失败
				  alert('添加失败！')
			      }
			  })
       }
     #+END_SRC
   * 设置根路径
     * Vue.http.options.root = 'http://vue/root/'
     * 单独请求的url不加斜杠
   * 全局启用emulateJSON：Vue.http.options.emulateJSON = true
** Vue中的动画
** Vue组件
   * 作用：拆分vue实例代码量
   * 创建组件
     * 创建组件：使用Vue.extend
       #+BEGIN_SRC js
	 var com1 = Vue.extend({
	     template: '<h3>这是通过vue.extend创建的组件</h3>'
	 })
	 Vue.component('myCom1', com1) //驼峰命名使用‘-’
	 //html中应用<my-com1></my-com1>
       #+END_SRC
     * 创建组件：直接使用Vue.component
       #+BEGIN_SRC js
	 Vue.component('myCom2', {
	     template: '<h3>创建组件的第二种方式</h3>'
	 })
       #+END_SRC
     * 创建组件：使用<template></template>标签
       #+BEGIN_SRC js
	 Vue.component('myCom3', {
	     template: '#temp1'
	 })
       
	 <template id="temp1">
	     <h3>这是创建组件最好的方式</h3>
	 </template>
       #+END_SRC
     * 也可以在实例内部定义私有组件，使用使用components属性
   * 组件的data和methos
     * 组件可以有自己的data
     * 组件中的data必须是一个方法
     * data方法必须返回一个对象，使用方式与实例一致
       #+BEGIN_SRC js
	 Vue.component('mycom', {
	     template: '<h3>{{ msg }}</h3>',
	     data: function(){
		 return {
		     msg: '组件data定义的数据'
		 }
	     }
	 })
       #+END_SRC
   * 组件切换：
     * v-if, v-else
     * 使用component标签 <component :is="comName"></component>

   * 父子组件
     * 子组件无法访问父组件的data和methods
     * 可以在引用子组件的时候通过属性绑定把数据传递给子组件，然后在子组件内部props数组中定义
     * 子组件的*data*数据是自身私有的，比如从ajax请求的数据。
     * 子组件的*props*数据是父组件传递的
     * data数据可读可写，props数据只读

   * 父组件传递方法给子组件
     * 在子组件的引用中通过事件绑定 @func="show"
     * 在子组件的模版中定义事件
     * 在组件对象字面量的methods属性中调用方法：this.$emit('func')
     * 可以向父组件传参

   * 父组件引用子组件的数据和方法(ref)
     * 获取dom元素：在标签身上加ref属性，如：<h3 ref='myh3'>content</h3>, 调用this.$refs.myh3.innerText
     * ref放在组件的引用上，可以获取组件的data和methods
** Vue路由
   * 前端路由：通过hash实现，在单页面跳转
     #+BEGIN_SRC js
       var login = {
	   template: '<h2>登陆组件</h2>'  //定义模版对象
       }
       var routerObj = new VueRouter({
	   routes: [
	       {path: '/', redirect: '/login'}, //重定向
	       {path: '/login', component: login},
	       {path: '/register', component: register} //component能是名称的属性值必须是属性模版对象
	   ] //routes属性为数组对象
       })
       var vm = new Vue({
	   router: routerObj //在vm实例注册路由对象
       })

       //使用router-view标签在页面加载
       // <router-view></router-view>
     #+END_SRC

   * 路由链接
     #+BEGIN_SRC js
       <router-link to="/login">登陆</router-link> //默认渲染为a
       <router-link to="/login" tag="span">登陆</router-link> //通过tag改变渲染成的标签类型
     #+END_SRC

   * 路由标签样式
     * 在路由的构造选项中修改 linkActiveClass的值(可使用bootstrap默认类或自定义)
     * 直接使用的默认的类 router-link-active,设置其样式即可
   
   * 路由传参
     * 在路由中使用query查询字符串：path不用变，路由要变：<router-link to="/login?id='12'>登陆<router-link> 获取id：this.$route.query.id
     * 在路由中使用params传参：{path: 'login/:id/:name'}，路由：<router- link to="/login/12>登陆<router-link> 获取id：this.$route.params.id
   
   * 路由嵌套
     * 在路由构造选项中增加children属性，其值也是一个数组对象，在数组中加入子路由path，path前面不加'/',否则以根路径请求

   * 路由命名视图
     * 同一个路由对应多个组件，在<router-view></router-view>中通过name属性区分

   * watch属性监视data中指定数据的变化，触发watch中的处理函数

   * watch监视路由地址的改变

     #+BEGIN_SRC js
       watch: {
	   '$route.path': function(newVal, oldVal){}
       }
     #+END_SRC

   * computed计算属性
     * 计算属性在引用的时候不用加括号
     * 只要function内部数据发生变化，计算属性就会重新求值
     * 计算属性的求值结果会被缓存，方便下次直接使用



** Webpack
   * 依赖安装
     * npm i webpack -g/-D
   * 概念：基于node.js开发的前端项目构建工具
   * 要解决的问题：页面静态资源较多时，1)导致加载速度慢，2)资源之间的依赖关系复杂
     * 1)合并，压缩，精灵图，图片的base64编码(Gulp)
     * 2)requireJS 或者 Webpack
   * 作用
     * 处理js文件之间的互相依赖关系
     * 处理js的兼容问题，把浏览器可以识别高版本的语法
       
       #+BEGIN_SRC js
	 //main.js
	 import $ from 'jquery'
	 $(function(){
	     $('li':odd).css('backgroundColor', 'yellow'),
	     $('li':even).css('backgroundColor', function () {
		 return '#' + 'D97634'
	     })
	 })
       #+END_SRC

   * 手动编译打包：使用命令"webpack [需要打包的文件路径] [打包后的文件路径]" 或者 编写配置文件"webpack.config.js"，然后直接使用"webpack"命令

     #+BEGIN_SRC js
       const path = require('path')
       module.exports = {
	   entry: path.join(__dirname, ''),
	   output:{
	       path: path.join(__dirname, ''),
	       filename: 'bundle.js'
	   } 
       }
     #+END_SRC

   * 使用webpack-dev-server工具实现自动打包编译
     * 安装：npm i webpack-dev-server -D(只能安装在本地，'-D'表示本地安装)
     * 由于安装在本地，无法在终端直接运行命令，需要1)在项目的package.json文件中配置 或 2)在webpack.config.js中配置:
       
       #+BEGIN_SRC js
	 //package.json
	 "scripts": {
	     "dev": "webpack-dev-server --open --port 3000 --contentBase src --hot" 
	     //'--open表示自动打开浏览器; --port表示指定运行端口; --contentBase表示项目运行时打开的项目路径; --hot表示不刷新重载'
	 }
       #+END_SRC

       #+BEGIN_SRC js
	 const webpack = require('webpack')
	 module.exports = {
	     devServer: {
		 open: true,
		 port: 3000,
		 contentBase: 'src',
		 hot: true
	     }
	     plugins: [
		 new webpack.HotModuleReplacementPlugin()
	     ]
	 }
       #+END_SRC

     * 运行命令：npm run dev(启动服务器)
     * 生成在bundle.js位置在根路径下，但是没有存放到物理磁盘上，而是托管到了内存中

   * 使用html-webpack-plugin插件
     * 安装：npm i html-webpack-plugin -D
     * 作用：
       * 不需要在页面中手动添加bundle.js的路径，插件自动处理了
       * 自动在内存中根据指定路径生成html
     * 在webpack.config.js中配置，放在plugins数组中

       #+BEGIN_SRC js
	 const path = require('path')
	 const htmlWebpackPlugin = require('html-webpack-plugin')
	 module.exports = {
	     plugins: [
		 new htmlWebpackPlugin({
		     template: path.join(__dirname, './src/index.html'), //磁盘上的文件
		     filename: 'index123.html' //内存中的文件，是一份拷贝
		 })
	     ]
	 }
       #+END_SRC

   * 处理css样式
     * 安装两个loader：npm i style-loader css-loader -D
     * 在webpack.config.js中增加module对象，在该对象的rules数组中设置第三方模块的匹配规则

       #+BEGIN_SRC js
	 import "./src/index.css"
	 module.exports = {
	     module: { //配置所有第三方模块加载器
		 rules: [ //配置第三方模块的匹配规则
		     { test: /\.css$/, use: ['style-loader', 'css-loader'] },
		 ]
	     }
	 }
       #+END_SRC

     * 处理过程：
       * 发现要处理的文件不是js文件，到配置文件中找第三方loader的匹配
       * 找到则调用对应的loader处理
       * 调用loader的时候从后往前，并把结果依次向前一个loader传递
       * 最后传递给webpack打包合并
     * 其他类型css文件的配置：less, scss(只能用cnpm安装)

       #+BEGIN_SRC js
	 module.exports = {
	     module: { //配置所有第三方模块加载器
		 rules: [ //配置第三方模块的匹配规则
		     { test: /\.css$/, use: ['style-loader', 'css-loader'] },
		     { test: /\.less$/, use: ['style-loader', 'css-loader', 'less-loader'] },
		     { test: /\.css$/, use: ['style-loader', 'css-loader', 'sass-loader'] },
		 ]
	     }
	 }
       #+END_SRC



